[[redirects]]
  from = "/api/*"
  to = "https://mes-aides.1jeune1solution.beta.gouv.fr/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "20.14.0"
