<script type="text/javascript">
if (window.location.hostname === 'mes-aides.gouv.fr') {
  var _paq = _paq || [];
  _paq.push(['trackPageView']);
  _paq.push(['enableLinkTracking']);
  (function() {
    var u='//stats.data.gouv.fr/';
    _paq.push(['setTrackerUrl', u+'piwik.php']);
    _paq.push(['setSiteId', 9]);
    var d=document, g=d.createElement('script'),
    s=d.getElementsByTagName('script')[0];
    g.type='text/javascript'; g.async=true; g.defer=true;
    g.src=u+'piwik.js'; s.parentNode.insertBefore(g,s);
  })();
}
</script>
