declareFirstChildHasIncomeRadio: 'yes-no-question [ng-class*="true"]',
hasSalaryCheckbox: 'uib-accordion label',
firstMonthInput: '#salaire_net_hors_revenus_exceptionnels-month_1',
secondMonthInput: '#salaire_net_hors_revenus_exceptionnels-month_2',
thirdMonthInput: '#salaire_net_hors_revenus_exceptionnels-month_3',
last12MonthsInput: '#salaire_net_hors_revenus_exceptionnels-year',
submitButton: 'button[type="submit"]',
errorMessage: '.text-danger',
