declareFirstChildHasIncomeRadio: 'yes-no-question [ng-class*="true"]',
hasSalaryCheckbox: 'uib-accordion label',
monthlyValueInput: '#salaire_net-monthly-value',
detailedButton: '.salaire_net .ressource-input-type-label a',
firstMonthInput: '#salaire_net-month_0',
secondMonthInput: '#salaire_net-month_1',
thirdMonthInput: '#salaire_net-month_2',
last12MonthsInput: '#salaire_net-year',
submitButton: 'button[type="submit"]',
errorMessage: '.text-danger',
