declareFirstChildHasIncomeRadio: 'yes-no-question [ng-class*="true"]',
hasSalaryCheckbox: 'uib-accordion label',
firstMonthInput: '#revenusSalarie-month_1',
secondMonthInput: '#revenusSalarie-month_2',
thirdMonthInput: '#revenusSalarie-month_3',
last12MonthsInput: '#revenusSalarie-year',
submitButton: 'button[type="submit"]',
errorMessage: '[role="alert"] p',
