title: 'h1',
prestationName: '.resultats-accordion:nth-child(' + PRESTATION_TO_TEST_POSITION + ') .description',
prestationMontant: '.resultats-accordion:nth-child(' + PRESTATION_TO_TEST_POSITION + ') .montant',
prestationMontantDetail: '.resultats-accordion:nth-child(' + PRESTATION_TO_TEST_POSITION + ') .montant-detail',
prestationYM2Warning: '.resultats-accordion:nth-child(' + PRESTATION_TO_TEST_POSITION + ') i.fa-warning',
openPrestationTabLink: '.resultats-accordion:nth-child(' + PRESTATION_TO_TEST_POSITION + ') a',
prestationDescription: '.resultats-accordion:nth-child(' + PRESTATION_TO_TEST_POSITION + ') p',
prestationMoreInfoLink: '.resultats-accordion:nth-child(' + PRESTATION_TO_TEST_POSITION + ') .btn-default',
prestationEngagerDemarchesLink: '.resultats-accordion:nth-child(' + PRESTATION_TO_TEST_POSITION + ') .btn-primary',

openPrimeActiviteLink: { a: 'Prime d’activité' },
requestPrimeActiviteLink: { a: 'Faire une demande' },

greyedPrestation: '.resultats-accordion-needs-n-2',
declareYM2ResourcesLink: { a: 'Déclarez vos ressources' },
