title: 'h1',
demandeurRevenuActiviteInput: '#salaire_imposable_ym2-demandeur',
suggestionText: '.help-block',
conjointChomageImposableInput: '#chomage_imposable-conjoint',
rfrInput: '#rfr',
submitButton: 'button[type="submit"]',
