title: 'h1',
demandeurRevenuActiviteInput: '#rncRevenusActivite-demandeur',
conjointAutresRevenusInput: '#rncAutresRevenus-conjoint',
rfrInput: '#rfr',
submitButton: 'button[type="submit"]',
errorMessage: '.text-danger',
globalErrorMessage: '.text-right .text-danger',
