root: ../../..

hackJamstackLoader: &hackJamstackLoader
  extension: 'yml'

benefitBase: &benefitBase
  required:
    - label
    - link

benefitProperties: &benefitProperties
  conditions:
    oneOf:
      - type: "null"
      - type: array
        items:
          type: string
  description:
    type: string
  floorAt:
    oneOf:
      - type: "null"
      - type: number
  form:
    oneOf:
      - type: "null"
      - type: string
  imgSrc:
    title: Logo de remplacement si nécessaire
    type: string
  interestFlag:
    oneOf:
      - type: "null"
      - type: string
  institution:
    type: string
  instructions:
    oneOf:
      - type: "null"
      - type: string
  label:
    title: Nom de l'aide
    type: string
  legend:
    type: string
  link:
    type: string
  montant:
    type: number
  participation:
    oneOf:
      - type: boolean
      - type: object
        description: TORM 
  periodicite:
    type: string
  prefix:
    title: Article défini
    description: L'ajout d'un article défini permet la formation de phrase grammaticalement correcte.
      Par exemple, dans la phrase « Comment obtenir l'aide exceptionnelle ? », on choisit le préfixe « l' ». Pour « Comment obtenir les aides au logement ? », on choisit le préfixe « les ».
    oneOf:
      - title: Préfix
        type: string
      - title: Préfix nul
        type: "null"
  private:
    type: boolean
  top:
    type: number
  teleservice:
    oneOf:
      - type: string
      - type: object
        additionalProperties: false
        properties:
          name:
            type: string
          query:
            type: object
            additionalProperties: false
            properties:
              vers:
                type: string
  type:
    type: string
  unit:
    oneOf:
      - type: "null"
      - type: string

collections:
  - name: test
    <<: *hackJamstackLoader
    folder: "data/test"
    schema:
      type: object
      additionalProperties: false
      properties:
        Q2hhbXAtMzAzNDI4NQ==:
          title: Adresse (Q2hhbXAtMzAzNDI4NQ==)
          oneOf:
            - title: Champs existant
              type: string
              enum: [A, B, C]
            - title: Nouveau champ
              type: string

  - name: institutions
    <<: *hackJamstackLoader
    folder: "data/institutions"
    schema:
      type: object
      additionalProperties: false
      required:
        - code_siren
        - name
        - type
      properties:
        code_insee:
          type: string
#          pattern: .{2,5}
        code_siren:
          type: string
          pattern: "^[1-9]{1}[0-9]{8}$"
        department:
          type: string
        etablissements:
          type: array
        imgSrc:
          type: string
        name:
          type: string
        prefix:
          type: string
        repository:
          type: string
        type:
          type: string
        top:
          type: number
      allOf:
        - anyOf:
          - properties:
              type:
                enum: [departement, region, commune]
            required:
              - code_insee
          - properties:
              type:
                enum: [epci, national, msa, caf, autre]

  - name: benefits_javascript
    <<: *hackJamstackLoader
    folder: "data/benefits/javascript"
    schema:
      <<: *benefitBase
      type: object
      additionalProperties: false
      properties:
        <<: *benefitProperties
        conditions_generales:
          type: array
        profils:
          type: array

  - name: benefits_openfisca
    <<: *hackJamstackLoader
    folder: "data/benefits/openfisca"
    schema:
      <<: *benefitBase
      type: object
      additionalProperties: false
      properties:
        <<: *benefitProperties
        entity:
          type: string
        etablissements:
          type: array
        forms:
          type: object
        isBaseRessourcesPatrimoine:
          type: boolean
        isBaseRessourcesYearMinusTwo:
          type: boolean
        msa:
          type: boolean
        openfiscaPeriod:
          type: string
        openfisca_eligibility_source:
          type: string
        setToZeroRecently:
          type: boolean
        skip_schema_check:
          type: boolean
        teleservices:
          type: object
