env:
  browser: true
  commonjs: true
rules:
  space-unary-ops:
    - error
    - words: false
      nonwords: true
      overrides:
        "-": false
  no-console: 0
globals:
  _: true
  angular: true
  d3: true
  jsyaml: true
  moment: true
