PRESTATION_TO_TEST_POSITION = 2
PRESTATION_NAME = /Prime d’activité/
PRESTATION_ID = 'ppa'
PRESTATION_DESCRIPTION = /revenus/
HAS_PRESTATION_WARNING = false
HAS_PRESTATION_ENGAGER_DEMARCHES_LINK = true
